# == Schema Information
#
# Table name: genes
#
#  id                :bigint(8)        not null, primary key
#  name              :string
#  original_sequence :text
#  sequence          :text
#  user_id           :bigint(8)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

FactoryBot.define do
  factory :gene do
    user { User.find(1) || association(:user) }
    name { Faker::Lorem.word }
    original_sequence 'ATGGACGGGTCCGGGGAGCAGCCCAGAGGCGGGGGTGAGGCGGGAGGCAGACGGGCGGGAGGAGGGCGAGCCCCCTCGCCGGCCCGTCCGGGATCCTTCCTACCGGCCTGGGGCTGTGCGATCTCCAAGCACTGAGGGGCAGAAACTCCCGGATCGGGCGCTGCCAGCCTCCAGTCCCCTCCGTCCTCGGAGGTTCCTGGCTCTCTGATCCCCGTGTCCCGATCCCTGCCTCTCTGGCGCTCTCGGACCCTCGAGAACCAGGGGATCTCGGAAGCCAAGCCCCCGGGCAGGCCCGGGCTTGTCGCCCGCACCACTTCCTGCCTCTGGCACTGGTGGGAGGGGCGGGTCTCGCCTCTGCCCCCTCAGGCCAGGGGTCTGGATGCATATAGCGTTCCCCTAGCCTCTTTCCCCGGGGAGAATGTAGGATACAGGCCCAGCCTCCTGGCCTTTCTCCATCAGGGACTCAGTTGTCTGGGCCCCCCCGTCACTTTATCTGCTAGGGTCCCAGAAGTCCAGGGTCCCCAGCTCTGTCCTCCCTCAGGGGCCGTGAGTCTCCACAGTCTCCTGATCCCCTAGAACCCAAGAGTCCAGGTACCTCTTCCCTTCCTTTCTCCTCTAGGGCCCACCAGCTCTGAGCAGATCATGAAGACAGGGGCCCTTTTGCTTCAGGGGTGAGTTTGAGGTCTGATTATTGTGGCACAGATTTGAGGAGTGACACCCCGTTCTGATTCTGCACCCTCACTCCATCCCCACTCTAGTTTCATCCAGGATCGAGCAGGGCGAATGGGGGGGAGGCACCCGAGCTGGCCCTGGACCCGGTGCCTCAGGATGCGTCCACCAAGAAGCTGAGCGAGTGTCTCAAGCGCATCGGGGACGAACTGGACAGTAACATGGAGCTGCAG'
  end
end
