# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ac7deef6508c295d9b0a00566a344e9c5906478888cdecabadd3959e75267970ce7f32952c1fdba4599fe3f423ac7fa40f95b5b3d04d200646e90915fcad4e0

test:
  secret_key_base: 98d076224a70e7c1dba20161845798da1a177862550ee3c7181e3e73bea704c78a9d96515c68f918e305cb41dc0cfd649502648ff2fd100d99f4f73c85472c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
